FROM nvcr.io/nvidia/pytorch:24.01-py3

# Python log'ları buffere takılmasın
ENV PYTHONUNBUFFERED=1

# İhtiyacımız olan paketler
RUN pip install --no-cache-dir \
    jupyterlab \
    transformers \
    datasets \
    mlflow \
    boto3 \
    pyyaml \
    accelerate

# Çalışma dizini
WORKDIR /workspace

# Jupyter portu
EXPOSE 8888

# Jupyter Lab başlat
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]